//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Ompl.Base {

public enum AdvancedStateCopyOperation {
  NO_DATA_COPIED = 0,
  SOME_DATA_COPIED = 1,
  ALL_DATA_COPIED = 2
}

}
