//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Ompl.Base {

public class RealVectorStateSpace : StateSpace {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnDerived;

  internal RealVectorStateSpace(global::System.IntPtr cPtr, bool cMemoryOwn) : base(ompl_basePINVOKE.RealVectorStateSpace_SWIGSmartPtrUpcast(cPtr), true) {
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(RealVectorStateSpace obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnDerived) {
          swigCMemOwnDerived = false;
          ompl_basePINVOKE.delete_RealVectorStateSpace(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public class StateType : State {
    private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  
    internal StateType(global::System.IntPtr cPtr, bool cMemoryOwn) : base(ompl_basePINVOKE.RealVectorStateSpace_StateType_SWIGUpcast(cPtr), cMemoryOwn) {
      swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
    }
  
    internal static global::System.Runtime.InteropServices.HandleRef getCPtr(StateType obj) {
      return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
    }
  
    internal static global::System.Runtime.InteropServices.HandleRef swigRelease(StateType obj) {
      if (obj != null) {
        if (!obj.swigCMemOwn)
          throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
        global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
        obj.swigCMemOwn = false;
        obj.Dispose();
        return ptr;
      } else {
        return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  
    protected override void Dispose(bool disposing) {
      lock(this) {
        if (swigCPtr.Handle != global::System.IntPtr.Zero) {
          if (swigCMemOwn) {
            swigCMemOwn = false;
            ompl_basePINVOKE.delete_RealVectorStateSpace_StateType(swigCPtr);
          }
          swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
        }
        base.Dispose(disposing);
      }
    }
  
    public StateType() : this(ompl_basePINVOKE.new_RealVectorStateSpace_StateType(), true) {
      if (ompl_basePINVOKE.SWIGPendingException.Pending) throw ompl_basePINVOKE.SWIGPendingException.Retrieve();
    }
  
    public SWIGTYPE_p_double values {
      set {
        ompl_basePINVOKE.RealVectorStateSpace_StateType_values_set(swigCPtr, SWIGTYPE_p_double.getCPtr(value));
        if (ompl_basePINVOKE.SWIGPendingException.Pending) throw ompl_basePINVOKE.SWIGPendingException.Retrieve();
      } 
      get {
        global::System.IntPtr cPtr = ompl_basePINVOKE.RealVectorStateSpace_StateType_values_get(swigCPtr);
        SWIGTYPE_p_double ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_double(cPtr, false);
        if (ompl_basePINVOKE.SWIGPendingException.Pending) throw ompl_basePINVOKE.SWIGPendingException.Retrieve();
        return ret;
      } 
    }
  
  }

  public RealVectorStateSpace(uint dim) : this(ompl_basePINVOKE.new_RealVectorStateSpace__SWIG_0(dim), true) {
    if (ompl_basePINVOKE.SWIGPendingException.Pending) throw ompl_basePINVOKE.SWIGPendingException.Retrieve();
  }

  public RealVectorStateSpace() : this(ompl_basePINVOKE.new_RealVectorStateSpace__SWIG_1(), true) {
    if (ompl_basePINVOKE.SWIGPendingException.Pending) throw ompl_basePINVOKE.SWIGPendingException.Retrieve();
  }

  public void addDimension(double minBound, double maxBound) {
    ompl_basePINVOKE.RealVectorStateSpace_addDimension__SWIG_0(swigCPtr, minBound, maxBound);
    if (ompl_basePINVOKE.SWIGPendingException.Pending) throw ompl_basePINVOKE.SWIGPendingException.Retrieve();
  }

  public void addDimension(double minBound) {
    ompl_basePINVOKE.RealVectorStateSpace_addDimension__SWIG_1(swigCPtr, minBound);
    if (ompl_basePINVOKE.SWIGPendingException.Pending) throw ompl_basePINVOKE.SWIGPendingException.Retrieve();
  }

  public void addDimension() {
    ompl_basePINVOKE.RealVectorStateSpace_addDimension__SWIG_2(swigCPtr);
    if (ompl_basePINVOKE.SWIGPendingException.Pending) throw ompl_basePINVOKE.SWIGPendingException.Retrieve();
  }

  public void addDimension(string name, double minBound, double maxBound) {
    ompl_basePINVOKE.RealVectorStateSpace_addDimension__SWIG_3(swigCPtr, name, minBound, maxBound);
    if (ompl_basePINVOKE.SWIGPendingException.Pending) throw ompl_basePINVOKE.SWIGPendingException.Retrieve();
  }

  public void addDimension(string name, double minBound) {
    ompl_basePINVOKE.RealVectorStateSpace_addDimension__SWIG_4(swigCPtr, name, minBound);
    if (ompl_basePINVOKE.SWIGPendingException.Pending) throw ompl_basePINVOKE.SWIGPendingException.Retrieve();
  }

  public void addDimension(string name) {
    ompl_basePINVOKE.RealVectorStateSpace_addDimension__SWIG_5(swigCPtr, name);
    if (ompl_basePINVOKE.SWIGPendingException.Pending) throw ompl_basePINVOKE.SWIGPendingException.Retrieve();
  }

  public void setBounds(RealVectorBounds bounds) {
    ompl_basePINVOKE.RealVectorStateSpace_setBounds__SWIG_0(swigCPtr, RealVectorBounds.getCPtr(bounds));
    if (ompl_basePINVOKE.SWIGPendingException.Pending) throw ompl_basePINVOKE.SWIGPendingException.Retrieve();
  }

  public void setBounds(double low, double high) {
    ompl_basePINVOKE.RealVectorStateSpace_setBounds__SWIG_1(swigCPtr, low, high);
    if (ompl_basePINVOKE.SWIGPendingException.Pending) throw ompl_basePINVOKE.SWIGPendingException.Retrieve();
  }

  public RealVectorBounds getBounds() {
    RealVectorBounds ret = new RealVectorBounds(ompl_basePINVOKE.RealVectorStateSpace_getBounds(swigCPtr), true);
    if (ompl_basePINVOKE.SWIGPendingException.Pending) throw ompl_basePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override uint getDimension() {
    uint ret = ompl_basePINVOKE.RealVectorStateSpace_getDimension(swigCPtr);
    if (ompl_basePINVOKE.SWIGPendingException.Pending) throw ompl_basePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getDimensionName(uint index) {
    string ret = ompl_basePINVOKE.RealVectorStateSpace_getDimensionName(swigCPtr, index);
    if (ompl_basePINVOKE.SWIGPendingException.Pending) throw ompl_basePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int getDimensionIndex(string name) {
    int ret = ompl_basePINVOKE.RealVectorStateSpace_getDimensionIndex(swigCPtr, name);
    if (ompl_basePINVOKE.SWIGPendingException.Pending) throw ompl_basePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setDimensionName(uint index, string name) {
    ompl_basePINVOKE.RealVectorStateSpace_setDimensionName(swigCPtr, index, name);
    if (ompl_basePINVOKE.SWIGPendingException.Pending) throw ompl_basePINVOKE.SWIGPendingException.Retrieve();
  }

  public override double getMaximumExtent() {
    double ret = ompl_basePINVOKE.RealVectorStateSpace_getMaximumExtent(swigCPtr);
    if (ompl_basePINVOKE.SWIGPendingException.Pending) throw ompl_basePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override double getMeasure() {
    double ret = ompl_basePINVOKE.RealVectorStateSpace_getMeasure(swigCPtr);
    if (ompl_basePINVOKE.SWIGPendingException.Pending) throw ompl_basePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override void enforceBounds(State state) {
    ompl_basePINVOKE.RealVectorStateSpace_enforceBounds(swigCPtr, State.getCPtr(state));
    if (ompl_basePINVOKE.SWIGPendingException.Pending) throw ompl_basePINVOKE.SWIGPendingException.Retrieve();
  }

  public override bool satisfiesBounds(State state) {
    bool ret = ompl_basePINVOKE.RealVectorStateSpace_satisfiesBounds(swigCPtr, State.getCPtr(state));
    if (ompl_basePINVOKE.SWIGPendingException.Pending) throw ompl_basePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override void copyState(State destination, State source) {
    ompl_basePINVOKE.RealVectorStateSpace_copyState(swigCPtr, State.getCPtr(destination), State.getCPtr(source));
    if (ompl_basePINVOKE.SWIGPendingException.Pending) throw ompl_basePINVOKE.SWIGPendingException.Retrieve();
  }

  public override uint getSerializationLength() {
    uint ret = ompl_basePINVOKE.RealVectorStateSpace_getSerializationLength(swigCPtr);
    if (ompl_basePINVOKE.SWIGPendingException.Pending) throw ompl_basePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override void serialize(SWIGTYPE_p_void serialization, State state) {
    ompl_basePINVOKE.RealVectorStateSpace_serialize(swigCPtr, SWIGTYPE_p_void.getCPtr(serialization), State.getCPtr(state));
    if (ompl_basePINVOKE.SWIGPendingException.Pending) throw ompl_basePINVOKE.SWIGPendingException.Retrieve();
  }

  public override void deserialize(State state, SWIGTYPE_p_void serialization) {
    ompl_basePINVOKE.RealVectorStateSpace_deserialize(swigCPtr, State.getCPtr(state), SWIGTYPE_p_void.getCPtr(serialization));
    if (ompl_basePINVOKE.SWIGPendingException.Pending) throw ompl_basePINVOKE.SWIGPendingException.Retrieve();
  }

  public override double distance(State state1, State state2) {
    double ret = ompl_basePINVOKE.RealVectorStateSpace_distance(swigCPtr, State.getCPtr(state1), State.getCPtr(state2));
    if (ompl_basePINVOKE.SWIGPendingException.Pending) throw ompl_basePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override bool equalStates(State state1, State state2) {
    bool ret = ompl_basePINVOKE.RealVectorStateSpace_equalStates(swigCPtr, State.getCPtr(state1), State.getCPtr(state2));
    if (ompl_basePINVOKE.SWIGPendingException.Pending) throw ompl_basePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override void interpolate(State _from, State to, double t, State state) {
    ompl_basePINVOKE.RealVectorStateSpace_interpolate(swigCPtr, State.getCPtr(_from), State.getCPtr(to), t, State.getCPtr(state));
    if (ompl_basePINVOKE.SWIGPendingException.Pending) throw ompl_basePINVOKE.SWIGPendingException.Retrieve();
  }

  public override StateSampler allocDefaultStateSampler() {
    global::System.IntPtr cPtr = ompl_basePINVOKE.RealVectorStateSpace_allocDefaultStateSampler(swigCPtr);
    StateSampler ret = (cPtr == global::System.IntPtr.Zero) ? null : new StateSampler(cPtr, true);
    if (ompl_basePINVOKE.SWIGPendingException.Pending) throw ompl_basePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override State allocState() {
    global::System.IntPtr cPtr = ompl_basePINVOKE.RealVectorStateSpace_allocState(swigCPtr);
    State ret = (cPtr == global::System.IntPtr.Zero) ? null : new State(cPtr, false);
    if (ompl_basePINVOKE.SWIGPendingException.Pending) throw ompl_basePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override void freeState(State state) {
    ompl_basePINVOKE.RealVectorStateSpace_freeState(swigCPtr, State.getCPtr(state));
    if (ompl_basePINVOKE.SWIGPendingException.Pending) throw ompl_basePINVOKE.SWIGPendingException.Retrieve();
  }

  public override SWIGTYPE_p_double getValueAddressAtIndex(State state, uint index) {
    global::System.IntPtr cPtr = ompl_basePINVOKE.RealVectorStateSpace_getValueAddressAtIndex(swigCPtr, State.getCPtr(state), index);
    SWIGTYPE_p_double ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_double(cPtr, false);
    if (ompl_basePINVOKE.SWIGPendingException.Pending) throw ompl_basePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override void printState(State state, SWIGTYPE_p_std__ostream _out) {
    ompl_basePINVOKE.RealVectorStateSpace_printState(swigCPtr, State.getCPtr(state), SWIGTYPE_p_std__ostream.getCPtr(_out));
    if (ompl_basePINVOKE.SWIGPendingException.Pending) throw ompl_basePINVOKE.SWIGPendingException.Retrieve();
  }

  public override void printSettings(SWIGTYPE_p_std__ostream _out) {
    ompl_basePINVOKE.RealVectorStateSpace_printSettings(swigCPtr, SWIGTYPE_p_std__ostream.getCPtr(_out));
    if (ompl_basePINVOKE.SWIGPendingException.Pending) throw ompl_basePINVOKE.SWIGPendingException.Retrieve();
  }

  public override void registerProjections() {
    ompl_basePINVOKE.RealVectorStateSpace_registerProjections(swigCPtr);
    if (ompl_basePINVOKE.SWIGPendingException.Pending) throw ompl_basePINVOKE.SWIGPendingException.Retrieve();
  }

  public override void setup() {
    ompl_basePINVOKE.RealVectorStateSpace_setup(swigCPtr);
    if (ompl_basePINVOKE.SWIGPendingException.Pending) throw ompl_basePINVOKE.SWIGPendingException.Retrieve();
  }

}

}
