//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Ompl.Base {

public class RealVectorDeterministicStateSampler : DeterministicStateSampler {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnDerived;

  internal RealVectorDeterministicStateSampler(global::System.IntPtr cPtr, bool cMemoryOwn) : base(ompl_basePINVOKE.RealVectorDeterministicStateSampler_SWIGSmartPtrUpcast(cPtr), true) {
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(RealVectorDeterministicStateSampler obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnDerived) {
          swigCMemOwnDerived = false;
          ompl_basePINVOKE.delete_RealVectorDeterministicStateSampler(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public RealVectorDeterministicStateSampler(StateSpace space, DeterministicStateSampler.DeterministicSamplerType type) : this(ompl_basePINVOKE.new_RealVectorDeterministicStateSampler__SWIG_0(StateSpace.getCPtr(space), (int)type), true) {
    if (ompl_basePINVOKE.SWIGPendingException.Pending) throw ompl_basePINVOKE.SWIGPendingException.Retrieve();
  }

  public RealVectorDeterministicStateSampler(StateSpace space) : this(ompl_basePINVOKE.new_RealVectorDeterministicStateSampler__SWIG_1(StateSpace.getCPtr(space)), true) {
    if (ompl_basePINVOKE.SWIGPendingException.Pending) throw ompl_basePINVOKE.SWIGPendingException.Retrieve();
  }

  public RealVectorDeterministicStateSampler(StateSpace space, DeterministicSequence sequence_ptr, bool stretch) : this(ompl_basePINVOKE.new_RealVectorDeterministicStateSampler__SWIG_2(StateSpace.getCPtr(space), DeterministicSequence.getCPtr(sequence_ptr), stretch), true) {
    if (ompl_basePINVOKE.SWIGPendingException.Pending) throw ompl_basePINVOKE.SWIGPendingException.Retrieve();
  }

  public RealVectorDeterministicStateSampler(StateSpace space, DeterministicSequence sequence_ptr) : this(ompl_basePINVOKE.new_RealVectorDeterministicStateSampler__SWIG_3(StateSpace.getCPtr(space), DeterministicSequence.getCPtr(sequence_ptr)), true) {
    if (ompl_basePINVOKE.SWIGPendingException.Pending) throw ompl_basePINVOKE.SWIGPendingException.Retrieve();
  }

  public override void sampleUniform(State state) {
    ompl_basePINVOKE.RealVectorDeterministicStateSampler_sampleUniform(swigCPtr, State.getCPtr(state));
    if (ompl_basePINVOKE.SWIGPendingException.Pending) throw ompl_basePINVOKE.SWIGPendingException.Retrieve();
  }

  public override void sampleUniformNear(State state, State near, double distance) {
    ompl_basePINVOKE.RealVectorDeterministicStateSampler_sampleUniformNear(swigCPtr, State.getCPtr(state), State.getCPtr(near), distance);
    if (ompl_basePINVOKE.SWIGPendingException.Pending) throw ompl_basePINVOKE.SWIGPendingException.Retrieve();
  }

  public override void sampleGaussian(State state, State mean, double stdDev) {
    ompl_basePINVOKE.RealVectorDeterministicStateSampler_sampleGaussian(swigCPtr, State.getCPtr(state), State.getCPtr(mean), stdDev);
    if (ompl_basePINVOKE.SWIGPendingException.Pending) throw ompl_basePINVOKE.SWIGPendingException.Retrieve();
  }

}

}
