//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Ompl.Base {

public abstract class ValidStateSamplerAllocatorDirector : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ValidStateSamplerAllocatorDirector(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ValidStateSamplerAllocatorDirector obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ValidStateSamplerAllocatorDirector() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ompl_basePINVOKE.delete_ValidStateSamplerAllocatorDirector(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  protected abstract ValidStateSampler Invoke(SpaceInformation arg0) ;

  public ValidStateSamplerAllocatorDirector() : this(ompl_basePINVOKE.new_ValidStateSamplerAllocatorDirector(), true) {
    if (ompl_basePINVOKE.SWIGPendingException.Pending) throw ompl_basePINVOKE.SWIGPendingException.Retrieve();
    SwigDirectorConnect();
  }

  private void SwigDirectorConnect() {
    if (SwigDerivedClassHasMethod("Invoke", swigMethodTypes0))
      swigDelegate0 = new SwigDelegateValidStateSamplerAllocatorDirector_0(SwigDirectorMethodInvoke);
    ompl_basePINVOKE.ValidStateSamplerAllocatorDirector_director_connect(swigCPtr, swigDelegate0);
  }

  private bool SwigDerivedClassHasMethod(string methodName, global::System.Type[] methodTypes) {
    global::System.Reflection.MethodInfo methodInfo = this.GetType().GetMethod(methodName, global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Instance, null, methodTypes, null);
    bool hasDerivedMethod = methodInfo.DeclaringType.IsSubclassOf(typeof(ValidStateSamplerAllocatorDirector));
    return hasDerivedMethod;
  }

  private global::System.IntPtr SwigDirectorMethodInvoke(global::System.IntPtr arg0) {
    return ValidStateSampler.getCPtr(Invoke((arg0 == global::System.IntPtr.Zero) ? null : new SpaceInformation(arg0, true))).Handle;
  }

  public delegate global::System.IntPtr SwigDelegateValidStateSamplerAllocatorDirector_0(global::System.IntPtr arg0);

  private SwigDelegateValidStateSamplerAllocatorDirector_0 swigDelegate0;

  private static global::System.Type[] swigMethodTypes0 = new global::System.Type[] { typeof(SpaceInformation) };
}

}
